# Site settings
title: vecino 
email: info@vecino.com.co
description: "Estamos desarrollando tecnologías para la comunidad."
baseurl: ""
url: "http://vecino.com.co"
twitter_username: vecino_tw
github_username:  vecinorg
facebook_username: 490422051104332 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
